### PR TITLE
Fix github action instructions

### PR DESCRIPTION
**Pull request by staabm**
Closes https://github.com/Roave/BackwardCompatibilityCheck/issues/149

### CODE REVIEW

**Comment by Ocramius** [comment]
Thanks @staabm!

**Comment by Nyholm** [comment]
I guess this is closing my PR in #148.

**Comment by staabm** [comment]
@Nyholm oh sorry, didn't realize you did the same PR at the same day.

**Comment by Nyholm** [comment]
=)

**Pull request merged**
