### PR TITLE
Support `composer/composer:^2`

### LINKED ISSUE #304: Does not work with composer v2
```
max@pop-os:~/ha/php-skeleton$ composer require --dev roave/backward-compatibility-check
Using version ^5.0 for roave/backward-compatibility-check
./composer.json has been updated
Running composer update roave/backward-compatibility-check
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - composer/composer[1.10.7, ..., 1.10.22] require composer/semver ^1.0 -> found composer/semver[1.0.0, ..., 1.7.2] but the package is fixed to 3.2.4 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - roave/backward-compatibility-check 5.0.0 requires composer/composer ^1.10.7 -> satisfiable by composer/composer[1.10.7, ..., 1.10.22].
    - Root composer.json requires roave/backward-compatibility-check ^5.0 -> satisfiable by roave/backward-compatibility-check[5.0.0].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
```
# My composer version
```
max@pop-os:~/ha/php-skeleton$ composer --version
Composer version 2.0.13 2021-04-27 13:11:08
```

### PR DESCRIPTION
**Pull request by Legion112**
Fixes #304

### CODE REVIEW

**Comment by Ocramius** [comment]
The original issue report you raised seems to tell that you are running the
installation with `composer/composer:^1`?

**Comment by Legion112** [comment]
@Ocramius I added the output of my composer version to the issue.
It's version 2.\

**Comment by Ocramius** [comment]
@Legion112 `composer.lock` also needs updating here

**Comment by Ocramius** [comment]
To update `composer.lock`, please run a `composer update nothing` within the project

**Comment by Legion112** [comment]
@Ocramius  Why does the third-party package contains `composer.lock`? 
I think It should be deleted in order to allow install a different version.

**Comment by Ocramius** [comment]
@Legion112 `composer.lock` here has no effect on downstream packages: it is only here to keep builds stable / avoid moving dependencies between builds and code changes.

**Comment by Legion112** [comment]
@Ocramius 
I have tied several different ways to run the update. Nothing seems to work.
## Install the latest stable version of composer by 
```
max@pop-os:~/github/BackwardCompatibilityCheck$ composer self-update --2
You are already using the latest available Composer version 2.0.13 (2.x channel).
max@pop-os:~/github/BackwardCompatibilityCheck$ composer --version
Composer version 2.0.13 2021-04-27 13:11:08
max@pop-os:~/github/BackwardCompatibilityCheck$ composer update --lock
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires composer/composer == dev-master, found composer/composer[dev-master, 2.1.x-dev (alias of dev-master)] but it does not match your minimum-stability.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

```
## To install the latest commit of composer:
```
max@pop-os:~/github/BackwardCompatibilityCheck$ php ../composer-setup.php --snapshot 
All settings correct for using Composer
Downloading...

Composer (version 649087d6de158dc4da73a06c7759dec5932be5a5) successfully installed to: /home/max/github/BackwardCompatibilityCheck/composer.phar
Use it: php composer.phar

max@pop-os:~/github/BackwardCompatibilityCheck$ php ../composer.phar --version
Composer version 2.1-dev (2.1-dev+649087d6de158dc4da73a06c7759dec5932be5a5) 2021-05-04 14:47:54
max@pop-os:~/github/BackwardCompatibilityCheck$ ../composer.phar update --lock 
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires composer/composer == dev-master, found composer/composer[dev-master, 2.1.x-dev (alias of dev-master)] but it does not match your minimum-stability.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
max@pop-os:~/github/BackwardCompatibilityCheck$ ../composer.phar update --lock -W
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires composer/composer == dev-master, found composer/composer[dev-master, 2.1.x-dev (alias of dev-master)] but it does not match your minimum-stability.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
```
## Even have tried to use composer inside the vendor/bin directory
```
max@pop-os:~/github/BackwardCompatibilityCheck$ vendor/bin/composer update --lock
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires composer/composer == dev-master, found composer/composer[dev-master, 2.1.x-dev (alias of dev-master)] but it does not match your minimum-stability.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
max@pop-os:~/github/BackwardCompatibilityCheck$ vendor/bin/composer update --lock -W
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires composer/composer == dev-master, found composer/composer[dev-master, 2.1.x-dev (alias of dev-master)] but it does not match your minimum-stability.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
max@pop-os:~/github/BackwardCompatibilityCheck$ vendor/bin/composer update --lock --with-all-dependencies

```

**Comment by Ocramius** [comment]
Yeah, I just tried it locally and noticed the failures too :+1: 

No worries, at least we move forward :partying_face:

**Comment by MGatner** [comment]
@Ocramius Any idea when this will be released?

**Comment by Ocramius** [comment]
Releases are blocked by missing release automation:

 * #265
 * #244

**Comment by MGatner** [comment]
Ah, thanks for explaining! I didn't look back far enough. I'm using Nyholm's Action for now - I do love the options file feature it introduces.

**Pull request merged**
