### PR TITLE
Fix Travis builds

### LINKED ISSUE #169: Phar for version 4.2.0
Hi, it seems phar file is missing from assets of release 4.2.0:
https://github.com/Roave/BackwardCompatibilityCheck/releases

Could you please add it?

Thanks!

### PR DESCRIPTION
**Pull request by asgrim**
Fixes #169

### CODE REVIEW

**Comment by asgrim** [comment]
Note: nightly build removed, if we definitely want to add it back in, we need to research how to allow failures on it *without* using the `matrix` directive (since it conflicts with `jobs` it seems)

**Comment by Ocramius** [comment]
I'll probably be able to fix this up later tonight

**Comment by Ocramius** [comment]
This was much more work than what I was hoping for, but it's green now @_@

**Comment by asgrim** [comment]
> This was much more work than what I was hoping for, but it's green now @_@

That's why I left it for next week heh

**Pull request merged**
