### PR TITLE
Feature/support native property type short namespace

### PR DESCRIPTION
**Pull request by tomasnorre**
Add testcase for Docblock with full namespace to property with native type short namespace

### CODE REVIEW

**Comment by tomasnorre** [comment]
Sorry, did something wrong creating the PR. Must have based of the wrong branch. 
Will see how to clean this up.

**Comment by tomasnorre** [comment]
Should be fixed now.

**Review by Ocramius — CHANGES_REQUESTED** [review]
Note: because `roave/better-reflection:^5` removed all docblock support (by choice), we will likely need to go back to the drawing board about any docblock-based types.

 * https://github.com/Roave/BetterReflection/pull/900
 * https://github.com/Roave/BetterReflection/issues/899

**Comment by tomasnorre** [comment]
ok. I'll pause this for now, then. Let me know if I can help in any way.

**Comment by Ocramius** [comment]
Will close this one, as it is no longer applicable.

We will need to drag in something bigger than `roave/better-reflection` to analyze docblocks, in future.

**Pull request closed without merging**
