### PR TITLE
Remove extra redundant word in reported BC break text

### PR DESCRIPTION
**Pull request by greg0ire**
This is probably not deliberate, even if there are tests with the same issue :smile:

### CODE REVIEW

**Review by Ocramius — APPROVED** [review]
Indeed not deliberate :+1:

**Comment by Ocramius** [comment]
Thanks @greg0ire!

**Comment by greg0ire** [comment]
You're welcome welcome!

**Comment by asgrim** [comment]
iseewhatyoudidthere

**Comment by Ocramius** [comment]
Indeededed

**Pull request merged**
