### PR TITLE
Badges. Badges are important.

### PR DESCRIPTION
**Pull request by Ocramius**

### CODE REVIEW

**Comment by borNfreee** [comment]
You can also use Mutation Badge if you want to https://infection.github.io/guide/mutation-badge.html

**Comment by Ocramius** [comment]
@borNfreee that is a separate thing - I'm aiming at 0 mutations, but will do that in a separate patch

**Comment by borNfreee** [comment]
curious, what do you mean by "0 mutations"?

**Comment by Ocramius** [comment]
@borNfreee 0 escaped mutants, sorry :-)

**Comment by borNfreee** [comment]
alright ;)

**Pull request merged**
