### PR TITLE
Use native invocations instead of explicit __invoke()

### PR DESCRIPTION
**Pull request by Majkl578**
All these `->__invoke()` things are not cool when language provides native syntax...

### CODE REVIEW

**Review by Ocramius — CHANGES_REQUESTED** [review]
The reason for the explicit invocations is that the tooling (PHPStorm, specifically) doesn't yet detect them via "find usages", so I'd rather leave them in as we heavily rely on tge IDE for refactoring purposes.

**Comment by greg0ire** [comment]
IMHO the IDE should adapt to the code, not the other way around.

**Comment by Majkl578** [comment]
Well, if you are a hostage of your own IDE, then something is a bit wrong...

**Comment by Ocramius** [comment]
Yes, but since I heavily rely on it, I'm making a trade-off and keeping it until the issue is actually solved.

**Comment by Ocramius** [comment]
Yes, I'm hostage of it: wouldn't go with VIM unless paid at my usual hourly rate to do so 😆

**Comment by greg0ire** [comment]
We don't want more people, all 4 of us vimmers are just fine :P

**Comment by ostrolucky** [comment]
"things are not cool" is justification of this change? really? This change has multiple drawbacks, you better provide some practical reasons for this.

**Comment by Majkl578** [comment]
@Ocramius When I first saw your WIP PR, I thought _"Wow, callables, he's taking it to whole next level, chaining callables etc!"_.
I suppose I was wrong. As it is now, it's just a set of ugly underscored method calls.
Sorry for interrupting.

**Comment by Ocramius** [comment]
No, it also removes the need for a method name overall, moving the problem to just to the class name.

Another thing that is also immediately clear to consumers is that this is the only public API for each class, and it prevents creeping in multiple methods per class.

**Comment by Majkl578** [comment]
> it also removes the need for a method name overall

You still need to name it, be it ugly `__invoke()` or nice `invoke()`.

>  immediately clear to consumers is that this is the only public API

Not really sice you can have `__invoke()` and normal methods side by side.

> it prevents creeping in multiple methods per class

Just like any other class with any single public method.

**Comment by Majkl578** [comment]
@asgrim Just out of curiosity, can I have your opinion?

**Comment by Majkl578** [comment]
Reopening this as the PhpStorm bug has been fixed and it should land in next EAP. :tada:

**Comment by ostrolucky** [comment]
There are deeper issues with dynamic invocation, not a minor braces bug, like https://youtrack.jetbrains.com/issue/WI-34223

You also can't ctrl+click to go to method definition, not sure how do you imagine IDE to solve that.

**Comment by Majkl578** [comment]
Sounds like a good idea! 
/cc @carusogabriel @kukulich?

**Comment by kukulich** [comment]
I like the idea :)

**Comment by Ocramius** [comment]
BTW, PHPStorm now seems to correctly detect `__invoke` usages: issue can be re-evaluated

**Comment by kukulich** [comment]
https://github.com/slevomat/coding-standard/issues/899

**Comment by Ocramius** [comment]
Can be changed by adjusting `SlevomatCodingStandard.PHP.DisallowDirectMagicInvokeCall`

**Comment by Ocramius** [comment]
I've rebased your commits and merged it all into #323, thanks @Majkl578!

**Pull request closed without merging**
