### PR TITLE
#67 stub out dependencies that cannot be located by using empty classes

### LINKED ISSUE #67: `Roave\BetterReflection\Reflection\ReflectionClass` "XXX" could not be found in the located source
Hey there,

Great tool! Excited to use this!
I tried running this on https://github.com/api-platform/core on the 2.2 branch:
`bin/roave-backward-compatibility-check --from=v2.2.6 --to=HEAD`
but receive:
```
In IdentifierNotFound.php line 30:

  Roave\BetterReflection\Reflection\ReflectionClass "Doctrine\DBAL\Types\Type" could not be found in the located source
```

Couldn't immediately work out the problem to fix myself, so tracking an issue.

### PR DESCRIPTION
**Pull request by Ocramius**
Fixes #67 

@bendavies can I ask for a review here please, as well as checking if this allows you to integrate this tool with your project?

### CODE REVIEW

**Comment by Ocramius** [comment]
Btw, thanks @michaelcullum for the idea!

**Comment by Ocramius** [comment]
Shipping/releasing here, as I won't have time to do it later today or tomorrow, and it is indeed a blocker...

**Comment by bendavies** [comment]
Thanks. I'll have a look later! Can't right now sorry.

**Comment by bendavies** [comment]
After this PR i'm receiving this running on API platform.
```
PHP Fatal error:  Uncaught Error: Call to a member function getAst() on null in /Users/bendavies/Code/BackwardCompatibilityCheck/vendor/roave/better-reflection/src/NodeCompiler/CompileNodeToValue.php:121
Stack trace:
#0 /Users/bendavies/Code/BackwardCompatibilityCheck/vendor/roave/better-reflection/src/NodeCompiler/CompileNodeToValue.php(44): Roave\BetterReflection\NodeCompiler\CompileNodeToValue->compileClassConstFetch(Object(PhpParser\Node\Expr\ClassConstFetch), Object(Roave\BetterReflection\NodeCompiler\CompilerContext))
#1 /Users/bendavies/Code/BackwardCompatibilityCheck/vendor/nikic/php-parser/lib/PhpParser/ConstExprEvaluator.php(145): Roave\BetterReflection\NodeCompiler\CompileNodeToValue->Roave\BetterReflection\NodeCompiler\{closure}(Object(PhpParser\Node\Expr\ClassConstFetch))
#2 /Users/bendavies/Code/BackwardCompatibilityCheck/vendor/nikic/php-parser/lib/PhpParser/ConstExprEvaluator.php(152): PhpParser\ConstExprEvaluator->evaluate(Object(PhpParser\Node\Expr\ClassConstFetch))
#3 /Users/bendavies/Code/BackwardCompatibil in /Users/bendavies/Code/BackwardCompatibilityCheck/vendor/roave/better-reflection/src/NodeCompiler/CompileNodeToValue.php on line 121
```

reproduction:
```
git clone git://github.com/api-platform/core.git
git checkout 2.2
../BackwardCompatibilityCheck/bin/roave-backward-compatibility-check --from=v2.2.6 --to=HEAD
```

**Comment by Ocramius** [comment]
This usually happens when a constant cannot be located. If you have a reference to a non-existing class and then attempt to retrieve a constant from it, it will:

 1. Be stubbed out as an empty class
 2. The constant lookup will fail

I just reproduced this in `zendframework/zend-mvc` when comparing 2.x and `master`, but couldn't pin it down to a single constant. I will try to isolate the issue, but it looks like the scenario I described above, and we won't be able to do much about it besides turning it into a failed assertion. It is possible that without some core classes or extensions the sources would lead to an autoload-time error also in your project.

**Comment by Ocramius** [comment]
@bendavies see https://github.com/Roave/BetterReflection/pull/425 - that should at least lead to better exception messages for these scenarios. Not something the tool can fix though :-\

**Comment by Ocramius** [comment]
Also reported https://github.com/Roave/BackwardCompatibilityCheck/issues/77, since stubbing drags in some more issues, and is also incomplete (can't stub `interface`, `class` and `trait` separately)

**Pull request merged**
