### PR TITLE
#179 bump `nikolaposa/version` dependency to `4.0.0`

### LINKED ISSUE #37: Allow release versions such as `v1.2.3` and `release-1.2.3` (as well as other patterns recognized by composer)
Ref: https://github.com/Roave/ApiCompare/pull/35#discussion_r181588570

### PR DESCRIPTION
**Pull request by Ocramius**
Replaces #179
Fixes #179 
Fixes #37

### CODE REVIEW

**Comment by Ocramius** [comment]
Failures from #179 are expected:

```
[BC] CHANGED: The return type of Roave\BackwardCompatibility\Git\GetVersionCollection#fromRepository() changed from Version\VersionsCollection to the non-covariant Version\VersionCollection

[BC] CHANGED: The return type of Roave\BackwardCompatibility\Git\GetVersionCollection#fromRepository() changed from Version\VersionsCollection to Version\VersionCollection

[BC] CHANGED: The parameter $versions of Roave\BackwardCompatibility\Git\PickLastMinorVersionFromCollection#forVersions() changed from Version\VersionsCollection to a non-contravariant Version\VersionCollection

[BC] CHANGED: The return type of Roave\BackwardCompatibility\Git\GetVersionCollectionFromGitRepository#fromRepository() changed from Version\VersionsCollection to the non-covariant Version\VersionCollection

[BC] CHANGED: The parameter $versionsCollection of Roave\BackwardCompatibility\Git\PickVersionFromVersionCollection#forVersions() changed from Version\VersionsCollection to a non-contravariant Version\VersionCollection

[BC] CHANGED: The parameter $versionsCollection of Roave\BackwardCompatibility\Git\PickVersionFromVersionCollection#forVersions() changed from Version\VersionsCollection to Version\VersionCollection
```

**Comment by jdpedrie** [comment]
Can we get a release containing this fix?

**Comment by Ocramius** [comment]
Not yet: CI needs to go back to green first.

**Comment by Ocramius** [comment]
Seems like the failures on `master` are due to PHP 7.4.6, which has some very nasty bugs in `yield from`.

I think a release will require a `"conflict": {"php": "7.4.6"}` for now :-(

**Pull request merged**
